//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffiti_Api.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traffiti_Api.Controllers.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour ago.
        /// </summary>
        internal static string hour_en {
            get {
                return ResourceManager.GetString("hour_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 小时前.
        /// </summary>
        internal static string hour_sc {
            get {
                return ResourceManager.GetString("hour_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 小時前.
        /// </summary>
        internal static string hour_tc {
            get {
                return ResourceManager.GetString("hour_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently.
        /// </summary>
        internal static string recently_en {
            get {
                return ResourceManager.GetString("recently_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刚刚.
        /// </summary>
        internal static string recently_sc {
            get {
                return ResourceManager.GetString("recently_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剛剛.
        /// </summary>
        internal static string recently_tc {
            get {
                return ResourceManager.GetString("recently_tc", resourceCulture);
            }
        }
    }
}
